seed: 123
device: 'cpu' # cpu or cuda

input:
  path: datasets
  batch_size: 100

model:
  peer_normalization: 0.03
  momentum: 0.9 # Momentum to use for the running mean in peer normalization loss.

  hidden_dim: 100
  num_layers: 2

  p: 1.0 # p-norm to use for goodness function

training:
  epochs: 10

  learning_rate: 4e-5
  weight_decay: 12e-6
  momentum: 0.9

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  val_idx: -1 # -1: validate only once training has finished; n: validate every n epochs.
  final_test: False # Set to true to evaluate performance on test-set.

hydra:
  run:
    dir: logs
